2025-08-16 01:10:20 | INFO | MainProcess | boot | ===== Logging started for BTCUSDT/1s =====
2025-08-16 01:10:20 | INFO | MainProcess | root | [PATHS] initialized for BTCUSDT | 1s
========== DEVICE REPORT ==========
torch.cuda.is_available(): True
CUDA device_count: 1
  [0] NVIDIA A100-SXM4-40GB
Selected device index: 0 -> NVIDIA A100-SXM4-40GB
torch.get_num_threads(): 6
===================================
Traceback (most recent call last):
  File "D:\bot\Train_RL.py", line 341, in <module>
    main()
  File "D:\bot\Train_RL.py", line 337, in main
    train_one_file(args, data_file)
  File "D:\bot\Train_RL.py", line 145, in train_one_file
    df = read_one(data_file, opts=LoadOptions(numeric_only=True, add_features=False, safe=args.safe))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\bot\config\loader.py", line 172, in read_one
    df = tbl.to_pandas(types_mapper=None)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow\\array.pxi", line 889, in pyarrow.lib._PandasConvertible.to_pandas
  File "pyarrow\\table.pxi", line 5132, in pyarrow.lib.Table._to_pandas
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\site-packages\pyarrow\pandas_compat.py", line 824, in table_to_dataframe
    blocks = [
             ^
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\site-packages\pyarrow\pandas_compat.py", line 825, in <listcomp>
    _reconstruct_block(item, column_names, ext_columns_dtypes)
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\site-packages\pyarrow\pandas_compat.py", line 765, in _reconstruct_block
    arr = pandas_dtype.__from_arrow__(arr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\site-packages\pandas\core\arrays\string_.py", line 366, in __from_arrow__
    arr = arr.to_numpy(zero_copy_only=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
Exception in thread Thread-1 (_monitor):
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\multiprocessing\connection.py", line 328, in _recv_bytes
